### ISSUE TITLE
Document how to set up cors

### ISSUE THREAD

**Issue by akiratsai** [tadpol/MrMurano#59]
exosite cli does support `cors.expose_headers` to control cors exposed headers, see https://pypi.python.org/pypi/exosite

**Comment by tadpol** [comment]
Interim, `murano cors` to see what the current CORS are.  Then save what you want to a file and set it with `murano cors set`.

You can also set it in the ProjectFile.

Create `<project>.murano` and add:
```yaml
routes:
  cors: {"expose_headers": ["X-Foo"], <other stuff…> }
```

**Comment by akiratsai** [comment]
As a developer, I need to know how to set up cors config, so, if I just look up the documentation, I can not figure out what to fill in. I think it's better to provide either a schema file or even better, a file that murano cli can generate for me, so I don't need to worry about it, but also I can customize later.

```yaml
---
credentials: false
expose_headers:
  - X-Auth-Token
  - X-Client-Version
headers:
  - Accept
  - Authorization
  - Content-Type
  - Origin
methods:
  - DELETE
  - GET
  - POST
  - PUT
origin:
  - "file://"
  - "http://localhost:*"
  - "https://*.apps.exosite.io"
```
